# Generated by Django 3.2 on 2021-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('music', models.FileField(upload_to='music')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
